name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: compila
      run: g++ -Wall -std=c++11 arvore.cpp
      - name: roda
      run: ./a.out